"""Auto-generated by ADE Platform — sales_etl"""

from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.empty import EmptyOperator
from airflow.operators.python import PythonOperator


def extract(**context):
    print("Extracting data for sales_etl")


def transform(**context):
    print("Transforming data for sales_etl")


def load(**context):
    print("Loading data for sales_etl")


default_args = {
    "owner": "ade-platform",
    "depends_on_past": False,
    "email_on_failure": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
}

with DAG(
    dag_id="sales_etl",
    default_args=default_args,
    description="ETL pipeline: sales_etl",
    schedule="0 6 * * *",
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["ade-platform", "auto-generated"],
) as dag:
    start = EmptyOperator(task_id="start")
    extract_task = PythonOperator(task_id="extract", python_callable=extract)
    transform_task = PythonOperator(task_id="transform", python_callable=transform)
    load_task = PythonOperator(task_id="load", python_callable=load)
    end = EmptyOperator(task_id="end")

    start >> extract_task >> transform_task >> load_task >> end
